apps/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.index_view, name="home-index"),
    path(
        "member-role/<tenant_id>", views.tenant_member_role, name="member-role"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('accounts/', include('allauth.urls')),
    path("", include("apps.home.urls", namespace="home")),
    path("profile/", include("apps.users.urls", namespace="users")),
]

# Only used when DEBUG=True, whitenoise can serve files when DEBUG=False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/forms.py
from django.forms import ModelForm
from django import forms
from django.core.exceptions import ValidationError
import re
from apps.tenant_manager.models import Tenant


class TenantForm(ModelForm):
    class Meta:
        model = Tenant
        fields = ["name", "schema_name"]
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Add Name ..."}),
            "schema_name": forms.TextInput(
                attrs={"placeholder": "Add Subdomain ..."}
            ),
        }

    def clean_schema_name(self):
        schema_name = self.cleaned_data["schema_name"].lower()

        if not re.match(r"^[a-z0-9]+(?:-[a-z0-9]+)*$", schema_name):
            raise ValidationError(
                "Subdomains can only contain lowercase letters, numbers, and hyphens!"
            )

        if Tenant.objects.filter(schema_name=schema_name).exists():
            raise ValidationError("This subdomain is already taken.")

        return schema_name

apps/home/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import login
from django.conf import settings
from django_tenants.utils import schema_context

from apps.tenant_manager.models import Domain
from apps.tenant_manager.models import TenantMember
from apps.tenant_manager.models import Tenant
from .forms import TenantForm


def index_view(request):
    tenant_form = TenantForm()

    if request.method == "POST":
        tenant_form = TenantForm(request.POST)
        if tenant_form.is_valid():
            tenant = tenant_form.save()

            domain = Domain.objects.create(
                tenant=tenant,
                domain=f"{tenant.schema_name}.{settings.BASE_URL}",
                is_primary=True,
            )

            TenantMember.objects.create(
                user=request.user, tenant=tenant, is_admin=True
            )

            with schema_context(tenant.schema_name):
                request.user.backend = (
                    "allauth.account.auth_backends.AuthenticationBackend"
                )
                login(request, request.user)

            return redirect(f"http://{domain.domain}{settings.PORT}")

    # Check if user is a tenant member
    try:
        tenant_member = TenantMember.objects.get(
            user=request.user, tenant=request.tenant
        )
    except Exception:
        tenant_member = None

    # Get the list of tenants for the user
    if request.user.is_authenticated:
        user_tenants = TenantMember.objects.filter(user=request.user)
    else:
        user_tenants = []

    base_domain = f"{settings.BASE_URL}{settings.PORT}"

    if hasattr(request, "tenants"):
        template_name = "home/index.html"
    else:
        template_name = "home/index_tenant.html"

    context = {
        "tenant_form": tenant_form,
        "tenant_member": tenant_member,
        "user_tenants": user_tenants,
        "base_domain": base_domain,
        "member_roles": TenantMember.ROLE_CHOICES,
    }

    return render(
        request=request, template_name=template_name, context=context
    )


def tenant_member_role(request, tenant_id):
    if request.method == "POST":
        role = request.POST.get("role")
        tenant = Tenant.objects.get(id=tenant_id)

        tenant_member, created = TenantMember.objects.get_or_create(
            user=request.user,
            tenant=tenant,
        )
        tenant_member.role = role.lower()
        tenant_member.save()

        return redirect(
            f"http://{tenant.schema_name}.{settings.BASE_URL}{settings.PORT}"
        )

templates/home/index.html
{% extends 'layouts/blank.html' %}

{% block content %} 

    <div class="max-w-4xl mx-auto px-8 py-24">
        <h1>Dashboard</h1>
        {% if user.is_authenticated %}
        <div class="w-full mt-8 flex gap-6">
            
            <div class="w-1/2">
                <div class="mb-6">
                    <div x-data="{ open: false }" class="relative">

                        <div @click="open = !open" class="flex items-center justify-between block w-full p-4 border border-gray-300 rounded-lg cursor-pointer">
                            My Tenants
                            <img x-bind:class="open && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/000000/expand-arrow.png" alt="Dropdown" />
                        </div>
                    
                        <div x-show="open" x-cloak @click.outside="open = false" class="absolute w-full border border-gray-300 rounded-lg shadow-lg z-10">
                            <ul>
                                {% if user_tenants %}
                                    {% for user_tenant in user_tenants %}
                                    <li>
                                        <a href = 'http://{{ user_tenant.tenant.schema_name }}.{{ base_domain }}' class="block px-4 py-2 hover:bg-indigo-500 hover:text-white">
                                            {{ user_tenant.tenant.name }}
                                        </a>
                                    </li>
                                    {% endfor %}
                                {% else %}
                                    <li>
                                        <div class="block px-4 py-2 text-gray-400">No Tenants yet</div>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>

            </div>

            <div class="w-1/2 rounded-lg border border-gray-300 px-6 py-4">
                <h2>Create new Tenant</h2>
                <div class="mt-3">
                    <form method="POST">
                        {% csrf_token %}
                        {{ tenant_form.as_p }}
                        <button type="submit">Create</button>
                    </form>
                </div>
            </div>
        </div>
        {% else %}
        <button>
            <a href="{% url 'account_login' %}">Log In</a>
        </button>
        {% endif %}
    </div>

{% endblock %}

templates/home/index_tenant.html
{% extends 'layouts/blank.html' %}

{% block content %} 

    <div class="max-w-4xl mx-auto px-8 py-24">
        <h1>Welcome to {{ request.tenant.name }}</h1>

        {% if user.is_authenticated %}
            <h2>Hello {{ user.profile.name }}{% if tenant_member.is_admin %} (Admin){% endif %}</h2>

            {% if tenant_member %}
            <p>Great to have you!</p>
            {% endif %}
            
            <div class="flex gap-6 mt-8">
                <div class="w-1/2">
                    <form method="POST" action="{% url 'home:member-role' request.tenant.id %}">
                        {% csrf_token %}

                        <div x-data="{ selectedRole: '', open: false }" class="relative">
                            <div @click="open = !open" class="flex items-center justify-between block w-full p-4 border border-gray-300 rounded-lg cursor-pointer">
                                <span x-text="selectedRole ? selectedRole : 'My Role'"></span>
                                <img x-bind:class="open && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/000000/expand-arrow.png" alt="Dropdown" />
                            </div>
                        
                            <div x-show="open" x-cloak @click.outside="open = false" class="absolute w-full bg-white border border-gray-300 rounded-lg shadow-lg z-10">
                                <ul>
                                    {% if member_roles %}
                                        {% for key, label in member_roles %}
                                        <li @click="selectedRole = '{{ label }}'; open = false" class="block px-4 py-2 hover:bg-indigo-500 hover:text-white cursor-pointer">
                                            {{ label }}
                                        </li>
                                        {% endfor %}
                                    {% endif %}
                                </ul>
                            </div>
                        
                            <input type="hidden" name="role" x-model="selectedRole">
                        </div>

                        <button class="mt-2" type="submit">Submit</button>

                    </form>
                </div>

                <div class="mb-6 w-1/2">

                    {% if tenant_member %}
                    <div class="p-4 border border-gray-300 rounded-lg">
                        <div class="mb-6">
                            <h2 class="mb-1">Managers</h2>
                            {% for member in request.tenant.members.all %}
                                {% if member.role == 'manager' %}
                                    <a class="block hover:underline pl-4" href="{% url 'profile' member.user.username %}">{{ member.user.profile.name }} {% if member.is_admin %}(Admin){% endif %}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="mb-6">
                            <h2 class="mb-1">Designers</h2>
                            {% for member in request.tenant.members.all %}
                                {% if member.role == 'designer' %}
                                    <a class="block hover:underline pl-4" href="{% url 'profile' member.user.username %}">{{ member.user.profile.name }} {% if member.is_admin %}(Admin){% endif %}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div>
                            <h2 class="mb-1">Programmers</h2>
                            {% for member in request.tenant.members.all %}
                                {% if member.role == 'programmer' %}
                                    <a class="block hover:underline pl-4" href="{% url 'profile' member.user.username %}">{{ member.user.profile.name }} {% if member.is_admin %}(Admin){% endif %}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <button><a href="{% url 'account_login' %}">Log In</a></button>
        {% endif %}
    </div>

{% endblock %}